version: "3.9"

services:
  db:
    image: mysql:8.0  
    # lecteure ++///
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_net

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_net:
