apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: U3VwZXJTZWNyZXQxMjM=   # "SuperSecret123"
  mysql-user: d3BfdXNlcg==                   # "wp_user"
  mysql-password: d3BfcGFzczEyMw==           # "wp_pass123"
